# Generated by Django 5.2.6 on 2025-09-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('numDoors', models.PositiveSmallIntegerField()),
                ('roofType', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('fuelType', models.CharField(max_length=50)),
            ],
        ),
    ]
