# Generated by Django 5.2.6 on 2025-09-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(choices=[('', 'choose one'), ('gas', 'Gas'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('lp_gas', 'LP Gas')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='roofType',
            field=models.CharField(choices=[('', 'choose one'), ('sunroof', 'Sunroof'), ('convertable', 'Convertable'), ('solid roof', 'Solid Roof')], default='', max_length=50),
        ),
    ]
